name: Notify Teams on GitHub Events

on:
  push:
    branches:
      - main
  issues:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created, edited]
  workflow_dispatch:
  repository_dispatch:

jobs:
  notify_teams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure that TEAMS_WEBHOOK_URL is set
        run: |
          if [[ -z "${{ secrets.TEAMS_WEBHOOK_URL }}" ]]; then
            echo "Error: TEAMS_WEBHOOK_URL secret is not set."
            exit 1
          fi

      - name: Send notification to Teams
        run: |
          # Check the event type and send a Teams notification accordingly
          case "${{ github.event_name }}" in
            push)
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Push event triggered by '${{ github.actor }}' in repository '${{ github.repository }}'. Pushed to branch '${{ github.ref }}'\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            issues)
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Issue event triggered by '${{ github.actor }}' in repository '${{ github.repository }}'. Issue #${{ github.event.issue.number }}: '${{ github.event.issue.title }}'\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            issue_comment)
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Issue Comment event triggered by '${{ github.actor }}' in repository '${{ github.repository }}'. Comment on Issue #${{ github.event.issue.number }}: '${{ github.event.comment.body }}'\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            workflow_dispatch)
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Workflow Dispatch event triggered by '${{ github.actor }}' in repository '${{ github.repository }}'. Workflow '${{ github.workflow }}' was manually triggered.\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            repository_dispatch)
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Repository Dispatch event triggered by '${{ github.actor }}' in repository '${{ github.repository }}'. Custom event: '${{ github.event.action }}' received.\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            *)
              echo "Unhandled event type: ${{ github.event_name }}"
              ;;
          esac

