name: Direct Push using GitHub App Token

on:
  push:
    branches:
      - dev  # Trigger this workflow on pushes to the 'dev' branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  direct_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ISSUEREPOAPP_APP_ID }}  # GitHub App ID
          private-key: ${{ secrets.ISSUEREPOAPP_PRIVATE_KEY }}  # GitHub App private key

      - name: Configure Git
        run: |
          git config --global user.name "issuerepoapp bot"
          git config --global user.email "issuerepoapp-bot@users.noreply.github.com"

      - name: Modify test.md (or another file)
        run: |
          echo "Hello" >> test.md
          git add test.md
          git commit -m "Append 'Hello' to test.md" || echo "No changes to commit"

      - name: Push to main using GitHub App token
        run: |
          git remote set-url origin https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/${{ github.repository }}
          git push origin HEAD:main --force  # Pushing directly to main branch
