name: Push to Protected Main

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  push_to_main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Generate GitHub App Token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ secrets.ISSUEREPOAPP_APP_ID }}  # Your GitHub App ID
        private-key: ${{ secrets.ISSUEREPOAPP_PRIVATE_KEY }}  # Your GitHub App private key

    - name: Configure Git
      run: |
        # Set the Git user for the GitHub App
        git config --global user.name "issuerepoapp bot"  # Replace with your GitHub App's name
        git config --global user.email "issuerepoapp-bot@users.noreply.github.com"  # Replace with your GitHub App's email

    - name: Modify test.md
      run: |
        echo "Hello" >> test.md
        git add test.md
        git commit -m "Append 'Hello' to test.md" || echo "No changes to commit"

    - name: Push to Main using GitHub App Token
      run: |
        # Use GitHub App token for authentication and push to the main branch
        git push https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/${{ github.repository }} HEAD:main --force
