name: Push to Protected Main

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  push_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.ISSUEREPOAPP_APP_ID }}  # Use organization secret for App ID
          private_key: ${{ secrets.ISSUEREPOAPP_PRIVATE_KEY }}  # Use organization secret for Private Key

      - name: Configure Git
        run: |
          git config --global user.name "issuerepoapp bot"
          git config --global user.email "issuerepoapp-bot@users.noreply.github.com"

      - name: Modify test.md
        run: |
          echo "Hello" >> test.md
          git add test.md
          git commit -m "Append 'Hello' to test.md" || echo "No changes to commit"

      - name: Fetch All Branches from Remote
        run: |
          git fetch --all  # Fetch all branches from the remote repository
          git branch -r  # List all remote branches to confirm dev exists

      - name: Checkout main
        run: |
          git checkout main  # Ensure we're on the main branch
          git pull origin main  # Pull latest changes from remote main to sync

      - name: Merge dev into main
        run: |
          git fetch origin  # Fetch all branches from origin
          git branch -r  # List remote branches again for debugging
          git checkout main  # Ensure we are on the main branch
          git merge --no-ff origin/dev -m "Automated merge from dev to main"  # Merge dev into main
          git push origin main  # Push the changes to 'main'
