name: Push to Protected Main

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  push_to_main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate GitHub App Token
        id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.ISSUEREPOAPP_APP_ID }}  # Use organization secret for App ID
          private_key: ${{ secrets.ISSUEREPOAPP_PRIVATE_KEY }}  # Use organization secret for Private Key

      - name: Configure Git
        run: |
          git config --global user.name "issuerepoapp bot"
          git config --global user.email "issuerepoapp-bot@users.noreply.github.com"

      - name: Modify test.md
        run: |
          echo "Hello" >> test.md
          git add test.md
          git commit -m "Append 'Hello' to test.md" || echo "No changes to commit"

      - name: Fetch all remote branches
        run: |
          git fetch --all  # Fetch all branches from the remote repository

      - name: Checkout dev branch (or correct branch name)
        run: |
          git checkout dev || echo "dev branch does not exist, skipping merge"  # Replace with the correct branch name if necessary

      - name: Push Changes & Merge to Main
        env:
          GITHUB_TOKEN: ${{ steps.app_token.outputs.token }}  # Use GitHub App token for authentication
        run: |
          git fetch origin  # Fetch all branches from origin
          git checkout main  # Ensure we're on the main branch
          git merge --no-ff origin/dev -m "Automated merge from dev to main"  # Use the correct branch name if necessary
          git push origin main  # Push the changes to 'main'
