name: Notify Teams on GitHub Events

on:
  repository_dispatch:
    types: [github-event]  # The type of event to listen for

jobs:
  notify_teams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure TEAMS_WEBHOOK_URL is set
        run: |
          if [[ -z "${{ secrets.TEAMS_WEBHOOK_URL }}" ]]; then
            echo "Error: TEAMS_WEBHOOK_URL secret is not set."
            exit 1
          fi

      - name: Send notification to Teams
        run: |
          case "${{ github.event.action }}" in
            push)
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Push event triggered in repository '${{ github.repository }}'.\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            issues)
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Issue event in repository '${{ github.repository }}'. Issue #${{ github.event.issue.number }}: '${{ github.event.issue.title }}'\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            issue_comment)
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Issue Comment event triggered in repository '${{ github.repository }}'. Comment on Issue #${{ github.event.issue.number }}: '${{ github.event.comment.body }}'\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            *)
              echo "Unhandled event type: ${{ github.event.action }}"
              ;;
          esac
