name: Trigger Central Notification

on:
  push:
  issues:
  issue_comment:

jobs:
  call-central:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to Central Repo
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/SX-SMHD/New/dispatches \
            -d '{"event_type": "${{ github.event_name }}", "client_payload": {"repo": "${{ github.repository }}", "actor": "${{ github.actor }}"}}'
