name: Notify Teams on GitHub Events

on:
  repository_dispatch:
    types: [github-event]  # This event type should match
jobs:
  notify_teams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure TEAMS_WEBHOOK_URL is set
        run: |
          if [[ -z "${{ secrets.TEAMS_WEBHOOK_URL }}" ]]; then
            echo "Error: TEAMS_WEBHOOK_URL secret is not set."
            exit 1
          fi

      - name: Send notification to Teams
        run: |
          case "${{ github.event.action }}" in
            push)
              # Push event details
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Push event triggered by '${{ github.actor }}' in repository '${{ github.event.client_payload.repository }}'. Pushed to branch '${{ github.event.client_payload.branch }}'.\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            issues)
              # Issue event details
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Issue event triggered by '${{ github.actor }}' in repository '${{ github.event.client_payload.repository }}'. Issue #${{ github.event.client_payload.issue_number }}: '${{ github.event.client_payload.issue_title }}'. Action: '${{ github.event.action }}'\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            issue_comment)
              # Issue comment event details
              curl -H 'Content-Type: application/json' \
                   -d "{\"text\": \"GitHub Issue Comment event triggered by '${{ github.actor }}' in repository '${{ github.event.client_payload.repository }}'. Comment on Issue #${{ github.event.client_payload.issue_number }}: '${{ github.event.client_payload.comment_body }}'\"}" \
                   "${{ secrets.TEAMS_WEBHOOK_URL }}" -v
              ;;
            *)
              echo "Unhandled event type: ${{ github.event.action }}"
              ;;
          esac
